version: "3.9"
services:
  db:
    image: "courier-db"
    logging:
      driver: none
    ports:
      - "5432:5432"
  api:
    image: "api"
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=random
      - AWS_SECRET_ACCESS_KEY=rando
    volumes:
      - "${PWD}:/courier/"
  aws:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

