version: "3.9"
services:
  db:
    image: "courier-db"
    logging:
      driver: none
    ports:
      - "5432:5432"
  api:
    image: "api"
    ports:
      - "8000:8000"
  # worker:
  #   image: "courier-worker"

